apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace | default "mysql" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - image: {{ .Values.image | default "mysql:5.7" }}
        name: {{ .Values.app }}
        env:
        - name: MYSQL_DATABASE
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: MYSQL_ROOT_PASSWORD
