apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.app }}
        env:
        - name: MYSQL_DATABASE
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: dbname
        - name: MYSQL_USER
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: username
        - name: MYSQL_PASSWORD
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
                  secretKeyRef:
                          name: mysql
                          key: rootpassword
