apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: {{ .Values.namespace | default "mysql" }}
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
        MYSQL_DATABASE: {{ .Values.MYSQL_DATABASE | b64enc }} #d29yZHByZXNz #wordpress
        MYSQL_USER: {{ .Values.MYSQL_USER | b64enc }}  #Z292aW5k #govind
        MYSQL_PASSWORD: {{ .Values.MYSQL_PASSWORD | b64enc }}  #cmVkaGF0 #redhat
        MYSQL_ROOT_PASSWORD: {{ .Values.MYSQL_ROOT_PASSWORD | b64enc }}  #cmVkaGF0  #redhat
