apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
        dbname: d29yZHByZXNz #wordpress
        username: Z292aW5k #govind
        password: cmVkaGF0 #redhat
        rootpassword: cmVkaGF0  #redhat
