apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
          - port: 81
