apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace | default "mysql" }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
          - port: {{ .Values.port | default 3306 }}
            targetPort: {{ .Values.targetPort | default 3306 }}
